// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTOrder = "t_order"

// TOrder mapped from table <t_order>
type TOrder struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键id
	OrderID      string    `gorm:"column:order_id;not null" json:"order_id"`                               // 订单编号
	OrderType    int32     `gorm:"column:order_type;not null" json:"order_type"`                           // 订单类型：0->正常订单；1->秒杀订单等
	OrderStatus  int32     `gorm:"column:order_status;not null" json:"order_status"`                       // 订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单
	PayType      int32     `gorm:"column:pay_type;not null" json:"pay_type"`                               // 支付方式：0->未支付；1->支付宝；2->微信
	TradeNo      string    `gorm:"column:trade_no;not null" json:"trade_no"`                               // 交易号
	OrderAmount  int32     `gorm:"column:order_amount;not null" json:"order_amount"`                       // 订单总金额
	PayAmount    int32     `gorm:"column:pay_amount;not null" json:"pay_amount"`                           // 应付金额（实际支付金额）
	CouponID     int32     `gorm:"column:coupon_id;not null" json:"coupon_id"`                             // 优惠券id
	CouponAmount int32     `gorm:"column:coupon_amount;not null" json:"coupon_amount"`                     // 优惠券抵扣金额
	UserID       int32     `gorm:"column:user_id;not null" json:"user_id"`                                 // 用户id
	PayAt        time.Time `gorm:"column:pay_at;not null" json:"pay_at"`                                   // 支付时间
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName TOrder's table name
func (*TOrder) TableName() string {
	return TableNameTOrder
}
