// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTOrderItem = "t_order_item"

// TOrderItem mapped from table <t_order_item>
type TOrderItem struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键id
	OrderID         string    `gorm:"column:order_id;not null" json:"order_id"`                               // 订单编号
	ProductID       int32     `gorm:"column:product_id;not null" json:"product_id"`                           // 商品id
	ProductName     string    `gorm:"column:product_name;not null" json:"product_name"`                       // 商品名称
	ProductPrice    int32     `gorm:"column:product_price;not null" json:"product_price"`                     // 商品价格
	ProductQuantity int32     `gorm:"column:product_quantity;not null" json:"product_quantity"`               // 商品数量
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName TOrderItem's table name
func (*TOrderItem) TableName() string {
	return TableNameTOrderItem
}
