// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTCart = "t_cart"

// TCart mapped from table <t_cart>
type TCart struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                      // 主键id
	UserID       int32     `gorm:"column:user_id;not null" json:"user_id"`                                 // 用户id
	ProductID    int32     `gorm:"column:product_id;not null" json:"product_id"`                           // 商品id
	Quantity     int32     `gorm:"column:quantity;not null" json:"quantity"`                               // 商品数量
	DeleteStatus int32     `gorm:"column:delete_status" json:"delete_status"`                              // 是否删除
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"` // 创建时间
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"` // 更新时间
}

// TableName TCart's table name
func (*TCart) TableName() string {
	return TableNameTCart
}
