// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTCoupon = "t_coupon"

// TCoupon mapped from table <t_coupon>
type TCoupon struct {
	ID                      int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                            // 主键id
	CouponName              string    `gorm:"column:coupon_name;not null" json:"coupon_name"`                               // 优惠卷名称
	CouponType              int32     `gorm:"column:coupon_type;not null" json:"coupon_type"`                               // 优惠卷类型：0->全场通用；1->指定分类；2->指定商品
	CouponAmount            int32     `gorm:"column:coupon_amount;not null" json:"coupon_amount"`                           // 优惠卷金额
	CouponMinAmount         int32     `gorm:"column:coupon_min_amount;not null" json:"coupon_min_amount"`                   // 最低消费金额
	CouponStartTime         time.Time `gorm:"column:coupon_start_time;not null" json:"coupon_start_time"`                   // 优惠卷开始时间
	CouponEndTime           time.Time `gorm:"column:coupon_end_time;not null" json:"coupon_end_time"`                       // 优惠卷结束时间
	CouponStatus            int32     `gorm:"column:coupon_status;not null" json:"coupon_status"`                           // 优惠卷状态：0->未使用；1->已使用；2->已过期
	CouponUserID            int32     `gorm:"column:coupon_user_id;not null" json:"coupon_user_id"`                         // 用户id
	CouponProductCategoryID int32     `gorm:"column:coupon_product_category_id;not null" json:"coupon_product_category_id"` // 商品分类id
	CouponProductID         int32     `gorm:"column:coupon_product_id;not null" json:"coupon_product_id"`                   // 商品id
	CreatedAt               time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`       // 创建时间
	UpdatedAt               time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`       // 更新时间
}

// TableName TCoupon's table name
func (*TCoupon) TableName() string {
	return TableNameTCoupon
}
